*(*const<> (size_t); foo) { } *(*const (size_t)() ; foo) { }
/*backtrace:
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
No locals.
#1  0x000000000078ca87 in std::char_traits<char>::copy (__s1=0x7ffff5f5a010 "", __s2=0x41 <error: Cannot access memory at address 0x41>, __n=14190592) at /usr/include/c++/5/bits/char_traits.h:275
No locals.
#2  0x0000000000792e2a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy (__d=0x7ffff5f5a010 "", __s=0x41 <error: Cannot access memory at address 0x41>, __n=14190592) at /usr/include/c++/5/bits/basic_string.h:299
No locals.
#3  0x000000000079551f in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy_chars (__p=0x7ffff5f5a010 "", __k1=0x41 <error: Cannot access memory at address 0x41>, __k2=0xd88841 "s") at /usr/include/c++/5/bits/basic_string.h:342
No locals.
#4  0x0000000000793aab in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*> (this=0x7fffffffba20, __beg=0x41 <error: Cannot access memory at address 0x41>, __end=0xd88841 "s") at /usr/include/c++/5/bits/basic_string.tcc:229
        __dnew = 14190592
#5  0x0000000000791a44 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct_aux<char*> (this=0x7fffffffba20, __beg=0x41 <error: Cannot access memory at address 0x41>, __end=0xd88841 "s") at /usr/include/c++/5/bits/basic_string.h:195
No locals.
#6  0x000000000078f6e4 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*> (this=0x7fffffffba20, __beg=0x41 <error: Cannot access memory at address 0x41>, __end=0xd88841 "s") at /usr/include/c++/5/bits/basic_string.h:214
No locals.
#7  0x000000000078d310 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (this=0x7fffffffba20, __str=<error: Cannot access memory at address 0x81>) at /usr/include/c++/5/bits/basic_string.h:398
No locals.
#8  0x00000000008a1cb3 in std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int>::pair<unsigned int&, void> (this=0x7fffffffba20, __x=<error: Cannot access memory at address 0x81>, __y=@0x7fffffffb9a0: 0) at /usr/include/c++/5/bits/stl_pair.h:139
No locals.
#9  0x00000000008a1d2c in std::make_pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int&> (__x=<error: Cannot access memory at address 0x81>, __y=@0x7fffffffb9a0: 0) at /usr/include/c++/5/bits/stl_pair.h:281
No locals.
#10 0x0000000000897cec in CheckStl::string_c_str (this=0x7fffffffbad0) at lib/checkstl.cpp:1064
        numpar = 0
        func = {tokenDef = , argDef = , token = , arg = , retDef = , retType = , functionScope = , nestedIn = , argumentList = std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<Variable, std::allocator<Variable> >::_Node: 
, initArgCount = 0, type = Function::eFunction, access = Public, noexceptArg = , throwArg = , flags = 0}
        scope = {check = , className = "", classDef = , classStart = , classEnd = , functionList = std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<Function, std::allocator<Function> >::_Node: 
, functionMap = std::__debug::multimap with 1 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::multimap<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Function const*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Function const*> > >::_Rep_type: 
, varlist = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<Variable, std::allocator<Variable> >::_Node: 
, nestedIn = , nestedList = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<Scope*, std::allocator<Scope*> >::_Node: 
, numConstructors = 0, numCopyOrMoveConstructors = 0, usingList = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<Scope::UsingInfo, std::allocator<Scope::UsingInfo> >::_Node: 
, type = Scope::eGlobal, definedType = , definedTypes = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<Type*, std::allocator<Type*> >::_Node: 
, functionOf = , function = }
        printInconclusive = false
        printPerformance = true
        symbolDatabase = 0xd87ce0
        c_strFuncParam = std::__debug::multimap with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::multimap<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned int> > >::_Rep_type: 

#11 0x00000000008a0147 in CheckStl::runSimplifiedChecks (this=0xd60be0 <_ZN12_GLOBAL__N_18instanceE>, tokenizer=0x7fffffffbde0, settings=0x7fffffffd0d8, errorLogger=0x7fffffffd0a0) at lib/checkstl.h:59
        checkStl = {<Check> = {_vptr.Check = 0xa62a30 <vtable for CheckStl+16>, _tokenizer = 0x7fffffffbde0, _settings = 0x7fffffffd0d8, _errorLogger = 0x7fffffffd0a0, _name = "STL usage"}, <No data fields>}
#12 0x00000000008dbf21 in CppCheck::checkFile (this=0x7fffffffd0a0, code="*(*const<> (size_t); foo) { } *(*const (size_t)() ; foo) { }\n", FileName=0xd80c00 "crash321.cpp", checksums=std::__debug::set with 1 elements = {...}, internalErrorFound=@0x7fffffffc2ab: false) at lib/cppcheck.cpp:398
        timerSimpleChecks = {_str = "STL usage::runSimplifiedChecks", _timerResults = 0xd61340 <S_timerResults>, _start = 0, _showtimeMode = 0, _stopped = false}
        it = <_ZN12_GLOBAL__N_18instanceE>
        istr = <incomplete type>
        timer = {_str = "Tokenizer::tokenize", _timerResults = 0xd61340 <S_timerResults>, _start = 0, _showtimeMode = 0, _stopped = true}
        result = true
        timer3 = {_str = "Tokenizer::simplifyTokenList2", _timerResults = 0xd61340 <S_timerResults>, _start = 0, _showtimeMode = 0, _stopped = true}
        _tokenizer = {list = {_front = 0xd88290, _back = 0xd8ce80, _files = std::__debug::vector of length 1, capacity 1 = {"crash321.cpp"}, _settings = 0x7fffffffd0d8, _isC = false, _isCPP = true}, _settings = 0x7fffffffd0d8, _errorLogger = 0x7fffffffd0a0, _symbolDatabase = 0xd87ce0, _configuration = "", _typeSize = std::__debug::map with 12 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned int> > >::_Rep_type: 
, _varId = 0, _codeWithTemplates = false, m_timerResults = 0x0}
#13 0x00000000008da4c7 in CppCheck::processFile (this=0x7fffffffd0a0, filename="crash321.cpp", fileStream=...) at lib/cppcheck.cpp:239
        t = {_str = "Preprocessor::getcode", _timerResults = 0xd61340 <S_timerResults>, _start = 0, _showtimeMode = 0, _stopped = true}
        codeWithoutCfg = "*(*const<> (size_t); foo) { } *(*const (size_t)() ; foo) { }\n"
        it = ""
        filedata = "*(*const<> (size_t); foo) { } *(*const (size_t)() ; foo) { }\n"
        preprocessor = {static macroChar = 1 '\001', static missingIncludeFlag = false, static missingSystemIncludeFlag = false, _settings = 0x7fffffffd0d8, _errorLogger = 0x7fffffffd0a0, file0 = "crash321.cpp"}
        configurations = std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Node: 

        checksums = std::__debug::set with 1 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<unsigned long long, std::less<unsigned long long>, std::allocator<unsigned long long> >::_Rep_type: 

        checkCount = 1
        internalErrorFound = false
#14 0x00000000008d8ee4 in CppCheck::check (this=0x7fffffffd0a0, path="crash321.cpp") at lib/cppcheck.cpp:70
        fin = <incomplete type>
#15 0x0000000000799322 in CppCheckExecutor::check_internal (this=0x7fffffffdbd0, cppcheck=..., argv=0x7fffffffdd88) at cli/cppcheckexecutor.cpp:806
        i = {first = "crash321.cpp", second = 62}
        totalfilesize = 62
        processedsize = 0
        c = 0
        settings = @0x7fffffffd0d8: {_append = "", _enabled = std::__debug::set with 7 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _terminate = false, debug = false, debugwarnings = false, debugFalsePositive = false, dump = false, exceptionHandling = false, inconclusive = false, jointSuppressionReport = true, experimental = false, _errorsOnly = false, _inlineSuppressions = false, _verbose = false, _force = false, _relativePaths = false, _basePaths = std::__debug::vector of length 0, capacity 0, _xml = false, _xml_version = 1, _jobs = 1, _loadAverage = 0, _exitCode = 0, _outputFormat = "", _showtime = SHOWTIME_NONE, _includePaths = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Node: 
, _maxConfigs = 12, enforcedLang = Settings::None, nomsg = {_suppressions = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Suppressions::FileMatcher, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Suppressions::FileMatcher> > >::_Rep_type: 
}, nofail = {_suppressions = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Suppressions::FileMatcher, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Suppressions::FileMatcher> > >::_Rep_type: 
}, userDefines = "", userUndefs = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, userIncludes = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Node: 
, configExcludePaths = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, reportProgress = false, library = {use = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, leakignore = std::__debug::set with 473 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, functionconst = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, functionpure = std::__debug::set with 293 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, useretval = std::__debug::set with 332 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, containers = std::__debug::map with 8 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::Container, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::Container> > >::_Rep_type: 
, argumentChecks = std::__debug::map with 473 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__debug::map<int, Library::ArgumentChecks, std::less<int>, std::allocator<std::pair<int const, Library::ArgumentChecks> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__debug::map<int, Library::ArgumentChecks, std::less<int>, std::allocator<std::pair<int const, Library::ArgumentChecks> > > > > >::_Rep_type: 
, returnuninitdata = std::__debug::set with 1 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, defines = std::__debug::vector of length 0, capacity 0, allocid = 3, _files = std::__debug::set with 1 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _alloc = std::__debug::map with 5 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::_Rep_type: 
, _dealloc = std::__debug::map with 2 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::_Rep_type: 
, _noreturn = std::__debug::map with 483 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > >::_Rep_type: 
, _ignorefunction = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _reporterrors = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > >::_Rep_type: 
, _processAfterCode = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > >::_Rep_type: 
, _markupExtensions = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _keywords = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >::_Rep_type: 
, _executableblocks = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::CodeBlock, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::CodeBlock> > >::_Rep_type: 
, _exporters = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::ExportedFunctions, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::ExportedFunctions> > >::_Rep_type: 
, _importers = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >::_Rep_type: 
, _reflection = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::_Rep_type: 
, _formatstr = std::__debug::map with 26 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<bool, bool>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::pair<bool, bool> > > >::_Rep_type: 
, podtypes = std::__debug::map with 49 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::PodType, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::PodType> > >::_Rep_type: 
, platform_types = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::PlatformType, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::PlatformType> > >::_Rep_type: 
, platforms = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::Platform, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::Platform> > >::_Rep_type: 
}, rules = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<Settings::Rule, std::allocator<Settings::Rule> >::_Node: 
, checkConfiguration = false, checkLibrary = false, standards = {c = Standards::C11, cpp = Standards::CPP11, posix = false}, sizeof_bool = 1, sizeof_short = 2, sizeof_int = 4, sizeof_long = 8, sizeof_long_long = 8, sizeof_float = 4, sizeof_double = 8, sizeof_long_double = 16, sizeof_wchar_t = 4, sizeof_size_t = 8, sizeof_pointer = 8, platformType = Settings::Unspecified}
        std = true
        posix = true
        windows = true
        returnValue = 0
#16 0x0000000000798043 in CppCheckExecutor::check (this=0x7fffffffdbd0, argc=3, argv=0x7fffffffdd88) at cli/cppcheckexecutor.cpp:200
        cppCheck = {<ErrorLogger> = {_vptr.ErrorLogger = 0xa6a530 <vtable for CppCheck+16>}, _errorList = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Node: 
, _settings = {_append = "", _enabled = std::__debug::set with 7 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _terminate = false, debug = false, debugwarnings = false, debugFalsePositive = false, dump = false, exceptionHandling = false, inconclusive = false, jointSuppressionReport = true, experimental = false, _errorsOnly = false, _inlineSuppressions = false, _verbose = false, _force = false, _relativePaths = false, _basePaths = std::__debug::vector of length 0, capacity 0, _xml = false, _xml_version = 1, _jobs = 1, _loadAverage = 0, _exitCode = 0, _outputFormat = "", _showtime = SHOWTIME_NONE, _includePaths = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Node: 
, _maxConfigs = 12, enforcedLang = Settings::None, nomsg = {_suppressions = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Suppressions::FileMatcher, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Suppressions::FileMatcher> > >::_Rep_type: 
}, nofail = {_suppressions = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Suppressions::FileMatcher, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Suppressions::FileMatcher> > >::_Rep_type: 
}, userDefines = "", userUndefs = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, userIncludes = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Node: 
, configExcludePaths = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, reportProgress = false, library = {use = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, leakignore = std::__debug::set with 473 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, functionconst = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, functionpure = std::__debug::set with 293 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, useretval = std::__debug::set with 332 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, containers = std::__debug::map with 8 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::Container, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::Container> > >::_Rep_type: 
, argumentChecks = std::__debug::map with 473 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__debug::map<int, Library::ArgumentChecks, std::less<int>, std::allocator<std::pair<int const, Library::ArgumentChecks> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__debug::map<int, Library::ArgumentChecks, std::less<int>, std::allocator<std::pair<int const, Library::ArgumentChecks> > > > > >::_Rep_type: 
, returnuninitdata = std::__debug::set with 1 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, defines = std::__debug::vector of length 0, capacity 0, allocid = 3, _files = std::__debug::set with 1 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _alloc = std::__debug::map with 5 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::_Rep_type: 
, _dealloc = std::__debug::map with 2 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::_Rep_type: 
, _noreturn = std::__debug::map with 483 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > >::_Rep_type: 
, _ignorefunction = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _reporterrors = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > >::_Rep_type: 
, _processAfterCode = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > >::_Rep_type: 
, _markupExtensions = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _keywords = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >::_Rep_type: 
, _executableblocks = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::CodeBlock, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::CodeBlock> > >::_Rep_type: 
, _exporters = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::ExportedFunctions, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::ExportedFunctions> > >::_Rep_type: 
, _importers = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >::_Rep_type: 
, _reflection = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::_Rep_type: 
, _formatstr = std::__debug::map with 26 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<bool, bool>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::pair<bool, bool> > > >::_Rep_type: 
, podtypes = std::__debug::map with 49 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::PodType, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::PodType> > >::_Rep_type: 
, platform_types = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::PlatformType, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::PlatformType> > >::_Rep_type: 
, platforms = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::Platform, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::Platform> > >::_Rep_type: 
}, rules = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<Settings::Rule, std::allocator<Settings::Rule> >::_Node: 
, checkConfiguration = false, checkLibrary = false, standards = {c = Standards::C11, cpp = Standards::CPP11, posix = false}, sizeof_bool = 1, sizeof_short = 2, sizeof_int = 4, sizeof_long = 8, sizeof_long_long = 8, sizeof_float = 4, sizeof_double = 8, sizeof_long_double = 16, sizeof_wchar_t = 4, sizeof_size_t = 8, sizeof_pointer = 8, platformType = Settings::Unspecified}, _errorLogger = @0x7fffffffdbd0, cfg = "", exitcode = 0, _useGlobalSuppressions = true, tooManyConfigs = false, _simplify = true, fileInfo = std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<Check::FileInfo*, std::allocator<Check::FileInfo*> >::_Node: 
}
        settings = @0x7fffffffd0d8: {_append = "", _enabled = std::__debug::set with 7 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _terminate = false, debug = false, debugwarnings = false, debugFalsePositive = false, dump = false, exceptionHandling = false, inconclusive = false, jointSuppressionReport = true, experimental = false, _errorsOnly = false, _inlineSuppressions = false, _verbose = false, _force = false, _relativePaths = false, _basePaths = std::__debug::vector of length 0, capacity 0, _xml = false, _xml_version = 1, _jobs = 1, _loadAverage = 0, _exitCode = 0, _outputFormat = "", _showtime = SHOWTIME_NONE, _includePaths = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Node: 
, _maxConfigs = 12, enforcedLang = Settings::None, nomsg = {_suppressions = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Suppressions::FileMatcher, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Suppressions::FileMatcher> > >::_Rep_type: 
}, nofail = {_suppressions = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Suppressions::FileMatcher, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Suppressions::FileMatcher> > >::_Rep_type: 
}, userDefines = "", userUndefs = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, userIncludes = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Node: 
, configExcludePaths = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, reportProgress = false, library = {use = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, leakignore = std::__debug::set with 473 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, functionconst = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, functionpure = std::__debug::set with 293 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, useretval = std::__debug::set with 332 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, containers = std::__debug::map with 8 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::Container, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::Container> > >::_Rep_type: 
, argumentChecks = std::__debug::map with 473 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__debug::map<int, Library::ArgumentChecks, std::less<int>, std::allocator<std::pair<int const, Library::ArgumentChecks> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__debug::map<int, Library::ArgumentChecks, std::less<int>, std::allocator<std::pair<int const, Library::ArgumentChecks> > > > > >::_Rep_type: 
, returnuninitdata = std::__debug::set with 1 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, defines = std::__debug::vector of length 0, capacity 0, allocid = 3, _files = std::__debug::set with 1 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _alloc = std::__debug::map with 5 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::_Rep_type: 
, _dealloc = std::__debug::map with 2 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::_Rep_type: 
, _noreturn = std::__debug::map with 483 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > >::_Rep_type: 
, _ignorefunction = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _reporterrors = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > >::_Rep_type: 
, _processAfterCode = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > >::_Rep_type: 
, _markupExtensions = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _keywords = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >::_Rep_type: 
, _executableblocks = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::CodeBlock, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::CodeBlock> > >::_Rep_type: 
, _exporters = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::ExportedFunctions, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::ExportedFunctions> > >::_Rep_type: 
, _importers = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >::_Rep_type: 
, _reflection = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::_Rep_type: 
, _formatstr = std::__debug::map with 26 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<bool, bool>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::pair<bool, bool> > > >::_Rep_type: 
, podtypes = std::__debug::map with 49 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::PodType, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::PodType> > >::_Rep_type: 
, platform_types = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::PlatformType, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::PlatformType> > >::_Rep_type: 
, platforms = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::Platform, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::Platform> > >::_Rep_type: 
}, rules = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<Settings::Rule, std::allocator<Settings::Rule> >::_Node: 
, checkConfiguration = false, checkLibrary = false, standards = {c = Standards::C11, cpp = Standards::CPP11, posix = false}, sizeof_bool = 1, sizeof_short = 2, sizeof_int = 4, sizeof_long = 8, sizeof_long_long = 8, sizeof_float = 4, sizeof_double = 8, sizeof_long_double = 16, sizeof_wchar_t = 4, sizeof_size_t = 8, sizeof_pointer = 8, platformType = Settings::Unspecified}
#17 0x00000000007a3750 in main (argc=3, argv=0x7fffffffdd88) at cli/main.cpp:129
        exec = {<ErrorLogger> = {_vptr.ErrorLogger = 0xa3ca60 <vtable for CppCheckExecutor+16>}, _settings = 0x7fffffffd0d8, _errorList = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _files = std::__debug::map with 1 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >::_Rep_type: 
, time1 = 0, static exceptionOutput = <optimized out>, errorlist = false}


registers:
rax            0xffff80000931d831	-140737334093775
rbx            0xd88841	14190657
rcx            0x1b11000	28381184
rdx            0xd88800	14190592
rsi            0x41	65
rdi            0x7ffff5f5a010	140737319903248
rbp            0x7fffffffb5c0	0x7fffffffb5c0
rsp            0x7fffffffb598	0x7fffffffb598
r8             0xffffffff	4294967295
r9             0x0	0
r10            0x22	34
r11            0x246	582
r12            0x0	0
r13            0x1	1
r14            0x0	0
r15            0x0	0
rip            0x7ffff6fa0f70	0x7ffff6fa0f70 <__memcpy_sse2_unaligned+32>
eflags         0x10206	[ PF IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0


current instructions:
=> 0x7ffff6fa0f70 <__memcpy_sse2_unaligned+32>:	movdqu (%rsi),%xmm8
   0x7ffff6fa0f75 <__memcpy_sse2_unaligned+37>:	cmp    $0x20,%rdx
   0x7ffff6fa0f79 <__memcpy_sse2_unaligned+41>:	movdqu %xmm8,(%rdi)
   0x7ffff6fa0f7e <__memcpy_sse2_unaligned+46>:	movdqu -0x10(%rsi,%rdx,1),%xmm8
   0x7ffff6fa0f85 <__memcpy_sse2_unaligned+53>:	movdqu %xmm8,-0x10(%rdi,%rdx,1)
   0x7ffff6fa0f8c <__memcpy_sse2_unaligned+60>:	ja     0x7ffff6fa0fa0 <__memcpy_sse2_unaligned+80>
   0x7ffff6fa0f8e <__memcpy_sse2_unaligned+62>:	mov    %rdi,%rax
   0x7ffff6fa0f91 <__memcpy_sse2_unaligned+65>:	retq   
   0x7ffff6fa0f92 <__memcpy_sse2_unaligned+66>:	nopl   0x0(%rax)
   0x7ffff6fa0f96 <__memcpy_sse2_unaligned+70>:	nopw   %cs:0x0(%rax,%rax,1)
   0x7ffff6fa0fa0 <__memcpy_sse2_unaligned+80>:	movdqu 0x10(%rsi),%xmm8
   0x7ffff6fa0fa6 <__memcpy_sse2_unaligned+86>:	cmp    $0x40,%rdx
   0x7ffff6fa0faa <__memcpy_sse2_unaligned+90>:	movdqu %xmm8,0x10(%rdi)
   0x7ffff6fa0fb0 <__memcpy_sse2_unaligned+96>:	movdqu -0x20(%rsi,%rdx,1),%xmm8
   0x7ffff6fa0fb7 <__memcpy_sse2_unaligned+103>:	movdqu %xmm8,-0x20(%rdi,%rdx,1)
   0x7ffff6fa0fbe <__memcpy_sse2_unaligned+110>:	jbe    0x7ffff6fa0f8e <__memcpy_sse2_unaligned+62>


threads backtrace:

Thread 1 (Thread 0x7ffff7fc9740 (LWP 35064)):
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
#1  0x000000000078ca87 in std::char_traits<char>::copy (__s1=0x7ffff5f5a010 "", __s2=0x41 <error: Cannot access memory at address 0x41>, __n=14190592) at /usr/include/c++/5/bits/char_traits.h:275
#2  0x0000000000792e2a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy (__d=0x7ffff5f5a010 "", __s=0x41 <error: Cannot access memory at address 0x41>, __n=14190592) at /usr/include/c++/5/bits/basic_string.h:299
#3  0x000000000079551f in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy_chars (__p=0x7ffff5f5a010 "", __k1=0x41 <error: Cannot access memory at address 0x41>, __k2=0xd88841 "s") at /usr/include/c++/5/bits/basic_string.h:342
#4  0x0000000000793aab in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*> (this=0x7fffffffba20, __beg=0x41 <error: Cannot access memory at address 0x41>, __end=0xd88841 "s") at /usr/include/c++/5/bits/basic_string.tcc:229
#5  0x0000000000791a44 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct_aux<char*> (this=0x7fffffffba20, __beg=0x41 <error: Cannot access memory at address 0x41>, __end=0xd88841 "s") at /usr/include/c++/5/bits/basic_string.h:195
#6  0x000000000078f6e4 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*> (this=0x7fffffffba20, __beg=0x41 <error: Cannot access memory at address 0x41>, __end=0xd88841 "s") at /usr/include/c++/5/bits/basic_string.h:214
#7  0x000000000078d310 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (this=0x7fffffffba20, __str=<error: Cannot access memory at address 0x81>) at /usr/include/c++/5/bits/basic_string.h:398
#8  0x00000000008a1cb3 in std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int>::pair<unsigned int&, void> (this=0x7fffffffba20, __x=<error: Cannot access memory at address 0x81>, __y=@0x7fffffffb9a0: 0) at /usr/include/c++/5/bits/stl_pair.h:139
#9  0x00000000008a1d2c in std::make_pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int&> (__x=<error: Cannot access memory at address 0x81>, __y=@0x7fffffffb9a0: 0) at /usr/include/c++/5/bits/stl_pair.h:281
#10 0x0000000000897cec in CheckStl::string_c_str (this=0x7fffffffbad0) at lib/checkstl.cpp:1064
#11 0x00000000008a0147 in CheckStl::runSimplifiedChecks (this=0xd60be0 <_ZN12_GLOBAL__N_18instanceE>, tokenizer=0x7fffffffbde0, settings=0x7fffffffd0d8, errorLogger=0x7fffffffd0a0) at lib/checkstl.h:59
#12 0x00000000008dbf21 in CppCheck::checkFile (this=0x7fffffffd0a0, code="*(*const<> (size_t); foo) { } *(*const (size_t)() ; foo) { }\n", FileName=0xd80c00 "crash321.cpp", checksums=std::__debug::set with 1 elements = {...}, internalErrorFound=@0x7fffffffc2ab: false) at lib/cppcheck.cpp:398
#13 0x00000000008da4c7 in CppCheck::processFile (this=0x7fffffffd0a0, filename="crash321.cpp", fileStream=...) at lib/cppcheck.cpp:239
#14 0x00000000008d8ee4 in CppCheck::check (this=0x7fffffffd0a0, path="crash321.cpp") at lib/cppcheck.cpp:70
#15 0x0000000000799322 in CppCheckExecutor::check_internal (this=0x7fffffffdbd0, cppcheck=..., argv=0x7fffffffdd88) at cli/cppcheckexecutor.cpp:806
#16 0x0000000000798043 in CppCheckExecutor::check (this=0x7fffffffdbd0, argc=3, argv=0x7fffffffdd88) at cli/cppcheckexecutor.cpp:200
#17 0x00000000007a3750 in main (argc=3, argv=0x7fffffffdd88) at cli/main.cpp:129
*/
