 ( *const<> ( size_t ) ; foo ) { } * ( *const ( size_t ) ( ) ;> foo )< { }

/*backtrace:
#0  0x00007ffff6f36267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
        resultvar = 0
        pid = 63890
        selftid = 63890
#1  0x00007ffff6f37eca in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x7ffff791fc62, sa_sigaction = 0x7ffff791fc62}, sa_mask = {__val = {13896224, 140737219922256, 140737351974688, 140737340270144, 140737340270144, 1, 140737340270275, 1, 140737336819945, 10, 140737340270275, 140737353914144, 140737340270275, 1, 140737353916496, 140737219922128}}, sa_flags = -148080288, sa_restorer = 0x7ffff7fc9740}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff7879b5d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x00007ffff78779a6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#4  0x00007ffff78779f1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#5  0x00007ffff7877c09 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x00007ffff78781ac in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#7  0x000000000078c126 in __gnu_cxx::new_allocator<char>::allocate (this=0x7fffffffba10, __n=8223699814931777825) at /usr/include/c++/5/ext/new_allocator.h:104
No locals.
#8  0x000000000078aaa6 in std::allocator_traits<std::allocator<char> >::allocate (__a=..., __n=8223699814931777825) at /usr/include/c++/5/bits/alloc_traits.h:360
No locals.
#9  0x0000000000788d6a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create (this=0x7fffffffba10, __capacity=@0x7fffffffb640: 8223699814931777824, __old_capacity=0) at /usr/include/c++/5/bits/basic_string.tcc:157
No locals.
#10 0x00000000007899f2 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*> (this=0x7fffffffba10, __beg=0x2e64656c6c616320 <error: Cannot access memory at address 0x2e64656c6c616320>, __end=0xa084d8d58cd5ac40 <error: Cannot access memory at address 0xa084d8d58cd5ac40>) at /usr/include/c++/5/bits/basic_string.tcc:223
        __dnew = 8223699814931777824
#11 0x00000000007879d2 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct_aux<char*> (this=0x7fffffffba10, __beg=0x2e64656c6c616320 <error: Cannot access memory at address 0x2e64656c6c616320>, __end=0xa084d8d58cd5ac40 <error: Cannot access memory at address 0xa084d8d58cd5ac40>) at /usr/include/c++/5/bits/basic_string.h:195
No locals.
#12 0x000000000078561a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*> (this=0x7fffffffba10, __beg=0x2e64656c6c616320 <error: Cannot access memory at address 0x2e64656c6c616320>, __end=0xa084d8d58cd5ac40 <error: Cannot access memory at address 0xa084d8d58cd5ac40>) at /usr/include/c++/5/bits/basic_string.h:214
No locals.
#13 0x0000000000783270 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (this=0x7fffffffba10, __str=<error: Cannot access memory at address 0x2e64656c6c616320>) at /usr/include/c++/5/bits/basic_string.h:398
No locals.
#14 0x000000000089562f in std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int>::pair<unsigned int&, void> (this=0x7fffffffba10, __x=<error: Cannot access memory at address 0x2e64656c6c616320>, __y=@0x7fffffffb990: 0) at /usr/include/c++/5/bits/stl_pair.h:139
No locals.
#15 0x00000000008956a8 in std::make_pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int&> (__x=<error: Cannot access memory at address 0x2e64656c6c616320>, __y=@0x7fffffffb990: 0) at /usr/include/c++/5/bits/stl_pair.h:281
No locals.
#16 0x000000000088c2e2 in CheckStl::string_c_str (this=0x7fffffffbac0) at lib/checkstl.cpp:942
        numpar = 0
        func = {tokenDef = , argDef = , token = , arg = , retDef = , retType = , functionScope = , nestedIn = , argumentList = std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<Variable, std::allocator<Variable> >::_Node: 
, initArgCount = 0, type = Function::eFunction, access = Public, noexceptArg = , throwArg = , flags = 0}
        scope = {check = , className = "", classDef = , classStart = , classEnd = , functionList = std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<Function, std::allocator<Function> >::_Node: 
, functionMap = std::__debug::multimap with 1 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::multimap<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Function const*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Function const*> > >::_Rep_type: 
, varlist = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<Variable, std::allocator<Variable> >::_Node: 
, nestedIn = , nestedList = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<Scope*, std::allocator<Scope*> >::_Node: 
, numConstructors = 0, numCopyOrMoveConstructors = 0, usingList = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<Scope::UsingInfo, std::allocator<Scope::UsingInfo> >::_Node: 
, type = Scope::eGlobal, definedType = , definedTypes = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<Type*, std::allocator<Type*> >::_Node: 
, functionOf = , function = }
        printInconclusive = false
        printPerformance = true
        symbolDatabase = 0xd73620
        c_strFuncParam = std::__debug::multimap with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::multimap<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned int> > >::_Rep_type: 

#17 0x000000000089473d in CheckStl::runSimplifiedChecks (this=0xd47c00 <_ZN12_GLOBAL__N_18instanceE>, tokenizer=0x7fffffffbdd0, settings=0x7fffffffd0c8, errorLogger=0x7fffffffd090) at lib/checkstl.h:59
        checkStl = {<Check> = {_vptr.Check = 0xa4cbe0 <vtable for CheckStl+16>, _tokenizer = 0x7fffffffbdd0, _settings = 0x7fffffffd0c8, _errorLogger = 0x7fffffffd090, _name = "STL usage"}, <No data fields>}
#18 0x00000000008c83b3 in CppCheck::checkFile (this=0x7fffffffd090, code="( *const<> ( size_t ) ; foo ) { } * ( *const ( size_t ) ( ) ;> foo )< { }\n", FileName=0xd6d0a0 "crash327.cpp", checksums=std::__debug::set with 1 elements = {...}, internalErrorFound=@0x7fffffffc29b: false) at lib/cppcheck.cpp:398
        timerSimpleChecks = {_str = "STL usage::runSimplifiedChecks", _timerResults = 0xd48340 <S_timerResults>, _start = 0, _showtimeMode = 0, _stopped = false}
        it = <_ZN12_GLOBAL__N_18instanceE>
        istr = <incomplete type>
        timer = {_str = "Tokenizer::tokenize", _timerResults = 0xd48340 <S_timerResults>, _start = 0, _showtimeMode = 0, _stopped = true}
        result = true
        timer3 = {_str = "Tokenizer::simplifyTokenList2", _timerResults = 0xd48340 <S_timerResults>, _start = 0, _showtimeMode = 0, _stopped = true}
        _tokenizer = {list = {_front = 0xd73450, _back = 0xd74f70, _files = std::__debug::vector of length 1, capacity 1 = {"crash327.cpp"}, _settings = 0x7fffffffd0c8, _isC = false, _isCPP = true}, _settings = 0x7fffffffd0c8, _errorLogger = 0x7fffffffd090, _symbolDatabase = 0xd73620, _configuration = "", _typeSize = std::__debug::map with 12 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned int> > >::_Rep_type: 
, _varId = 0, _codeWithTemplates = false, m_timerResults = 0x0}
#19 0x00000000008c6959 in CppCheck::processFile (this=0x7fffffffd090, filename="crash327.cpp", fileStream=...) at lib/cppcheck.cpp:239
        t = {_str = "Preprocessor::getcode", _timerResults = 0xd48340 <S_timerResults>, _start = 0, _showtimeMode = 0, _stopped = true}
        codeWithoutCfg = "( *const<> ( size_t ) ; foo ) { } * ( *const ( size_t ) ( ) ;> foo )< { }\n"
        it = ""
        filedata = "( *const<> ( size_t ) ; foo ) { } * ( *const ( size_t ) ( ) ;> foo )< { }\n"
        preprocessor = {static macroChar = 1 '\001', static missingIncludeFlag = false, static missingSystemIncludeFlag = false, _settings = @0x7fffffffd0c8, _errorLogger = 0x7fffffffd090, file0 = "crash327.cpp"}
        configurations = std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Node: 

        checksums = std::__debug::set with 1 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<unsigned long long, std::less<unsigned long long>, std::allocator<unsigned long long> >::_Rep_type: 

        checkCount = 1
        internalErrorFound = false
#20 0x00000000008c5376 in CppCheck::check (this=0x7fffffffd090, path="crash327.cpp") at lib/cppcheck.cpp:70
        fin = <incomplete type>
#21 0x000000000078eff2 in CppCheckExecutor::check_internal (this=0x7fffffffdbc0, cppcheck=..., argv=0x7fffffffdd78) at cli/cppcheckexecutor.cpp:789
        i = {first = "crash327.cpp", second = 74}
        totalfilesize = 74
        processedsize = 0
        c = 0
        settings = @0x7fffffffd0c8: {_append = "", _enabled = std::__debug::set with 7 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _terminate = false, debug = false, debugnormal = false, debugwarnings = false, debugFalsePositive = false, dump = false, exceptionHandling = false, inconclusive = false, jointSuppressionReport = true, experimental = false, quiet = false, _inlineSuppressions = false, _verbose = false, _force = false, _relativePaths = false, _basePaths = std::__debug::vector of length 0, capacity 0, _xml = false, _xml_version = 1, _jobs = 1, _loadAverage = 0, _exitCode = 0, _outputFormat = "", _showtime = SHOWTIME_NONE, _includePaths = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Node: 
, _maxConfigs = 12, enforcedLang = Settings::None, nomsg = {_suppressions = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Suppressions::FileMatcher, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Suppressions::FileMatcher> > >::_Rep_type: 
}, nofail = {_suppressions = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Suppressions::FileMatcher, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Suppressions::FileMatcher> > >::_Rep_type: 
}, userDefines = "", userUndefs = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, userIncludes = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Node: 
, configExcludePaths = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, reportProgress = false, library = {use = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, leakignore = std::__debug::set with 565 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, functionconst = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, functionpure = std::__debug::set with 296 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, useretval = std::__debug::set with 365 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, containers = std::__debug::map with 8 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::Container, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::Container> > >::_Rep_type: 
, argumentChecks = std::__debug::map with 639 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__debug::map<int, Library::ArgumentChecks, std::less<int>, std::allocator<std::pair<int const, Library::ArgumentChecks> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__debug::map<int, Library::ArgumentChecks, std::less<int>, std::allocator<std::pair<int const, Library::ArgumentChecks> > > > > >::_Rep_type: 
, returnuninitdata = std::__debug::set with 1 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, defines = std::__debug::vector of length 0, capacity 0, allocid = 9, _files = std::__debug::set with 2 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _alloc = std::__debug::map with 17 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::_Rep_type: 
, _dealloc = std::__debug::map with 6 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::_Rep_type: 
, _noreturn = std::__debug::map with 664 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > >::_Rep_type: 
, _ignorefunction = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _reporterrors = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > >::_Rep_type: 
, _processAfterCode = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > >::_Rep_type: 
, _markupExtensions = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _keywords = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >::_Rep_type: 
, _executableblocks = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::CodeBlock, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::CodeBlock> > >::_Rep_type: 
, _exporters = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::ExportedFunctions, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::ExportedFunctions> > >::_Rep_type: 
, _importers = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >::_Rep_type: 
, _reflection = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::_Rep_type: 
, _formatstr = std::__debug::map with 28 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<bool, bool>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::pair<bool, bool> > > >::_Rep_type: 
, podtypes = std::__debug::map with 116 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::PodType, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::PodType> > >::_Rep_type: 
, platform_types = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::PlatformType, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::PlatformType> > >::_Rep_type: 
, platforms = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::Platform, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::Platform> > >::_Rep_type: 
}, rules = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<Settings::Rule, std::allocator<Settings::Rule> >::_Node: 
, checkConfiguration = false, checkLibrary = false, standards = {c = Standards::C11, cpp = Standards::CPP11, posix = true}, sizeof_bool = 1, sizeof_short = 2, sizeof_int = 4, sizeof_long = 8, sizeof_long_long = 8, sizeof_float = 4, sizeof_double = 8, sizeof_long_double = 16, sizeof_wchar_t = 4, sizeof_size_t = 8, sizeof_pointer = 8, platformType = Settings::Unspecified}
        std = true
        posix = true
        windows = true
        returnValue = 0
#22 0x000000000078dd13 in CppCheckExecutor::check (this=0x7fffffffdbc0, argc=4, argv=0x7fffffffdd78) at cli/cppcheckexecutor.cpp:183
        cppCheck = {<ErrorLogger> = {_vptr.ErrorLogger = 0xa53cd0 <vtable for CppCheck+16>}, _errorList = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Node: 
, _settings = {_append = "", _enabled = std::__debug::set with 7 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _terminate = false, debug = false, debugnormal = false, debugwarnings = false, debugFalsePositive = false, dump = false, exceptionHandling = false, inconclusive = false, jointSuppressionReport = true, experimental = false, quiet = false, _inlineSuppressions = false, _verbose = false, _force = false, _relativePaths = false, _basePaths = std::__debug::vector of length 0, capacity 0, _xml = false, _xml_version = 1, _jobs = 1, _loadAverage = 0, _exitCode = 0, _outputFormat = "", _showtime = SHOWTIME_NONE, _includePaths = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Node: 
, _maxConfigs = 12, enforcedLang = Settings::None, nomsg = {_suppressions = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Suppressions::FileMatcher, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Suppressions::FileMatcher> > >::_Rep_type: 
}, nofail = {_suppressions = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Suppressions::FileMatcher, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Suppressions::FileMatcher> > >::_Rep_type: 
}, userDefines = "", userUndefs = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, userIncludes = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Node: 
, configExcludePaths = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, reportProgress = false, library = {use = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, leakignore = std::__debug::set with 565 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, functionconst = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, functionpure = std::__debug::set with 296 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, useretval = std::__debug::set with 365 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, containers = std::__debug::map with 8 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::Container, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::Container> > >::_Rep_type: 
, argumentChecks = std::__debug::map with 639 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__debug::map<int, Library::ArgumentChecks, std::less<int>, std::allocator<std::pair<int const, Library::ArgumentChecks> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__debug::map<int, Library::ArgumentChecks, std::less<int>, std::allocator<std::pair<int const, Library::ArgumentChecks> > > > > >::_Rep_type: 
, returnuninitdata = std::__debug::set with 1 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, defines = std::__debug::vector of length 0, capacity 0, allocid = 9, _files = std::__debug::set with 2 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _alloc = std::__debug::map with 17 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::_Rep_type: 
, _dealloc = std::__debug::map with 6 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::_Rep_type: 
, _noreturn = std::__debug::map with 664 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > >::_Rep_type: 
, _ignorefunction = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _reporterrors = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > >::_Rep_type: 
, _processAfterCode = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > >::_Rep_type: 
, _markupExtensions = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _keywords = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >::_Rep_type: 
, _executableblocks = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::CodeBlock, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::CodeBlock> > >::_Rep_type: 
, _exporters = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::ExportedFunctions, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::ExportedFunctions> > >::_Rep_type: 
, _importers = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >::_Rep_type: 
, _reflection = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::_Rep_type: 
, _formatstr = std::__debug::map with 28 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<bool, bool>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::pair<bool, bool> > > >::_Rep_type: 
, podtypes = std::__debug::map with 116 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::PodType, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::PodType> > >::_Rep_type: 
, platform_types = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::PlatformType, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::PlatformType> > >::_Rep_type: 
, platforms = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::Platform, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::Platform> > >::_Rep_type: 
}, rules = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<Settings::Rule, std::allocator<Settings::Rule> >::_Node: 
, checkConfiguration = false, checkLibrary = false, standards = {c = Standards::C11, cpp = Standards::CPP11, posix = true}, sizeof_bool = 1, sizeof_short = 2, sizeof_int = 4, sizeof_long = 8, sizeof_long_long = 8, sizeof_float = 4, sizeof_double = 8, sizeof_long_double = 16, sizeof_wchar_t = 4, sizeof_size_t = 8, sizeof_pointer = 8, platformType = Settings::Unspecified}, _errorLogger = @0x7fffffffdbc0, cfg = "", exitcode = 0, _useGlobalSuppressions = true, tooManyConfigs = false, _simplify = true, fileInfo = std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<Check::FileInfo*, std::allocator<Check::FileInfo*> >::_Node: 
}
        settings = @0x7fffffffd0c8: {_append = "", _enabled = std::__debug::set with 7 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _terminate = false, debug = false, debugnormal = false, debugwarnings = false, debugFalsePositive = false, dump = false, exceptionHandling = false, inconclusive = false, jointSuppressionReport = true, experimental = false, quiet = false, _inlineSuppressions = false, _verbose = false, _force = false, _relativePaths = false, _basePaths = std::__debug::vector of length 0, capacity 0, _xml = false, _xml_version = 1, _jobs = 1, _loadAverage = 0, _exitCode = 0, _outputFormat = "", _showtime = SHOWTIME_NONE, _includePaths = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Node: 
, _maxConfigs = 12, enforcedLang = Settings::None, nomsg = {_suppressions = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Suppressions::FileMatcher, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Suppressions::FileMatcher> > >::_Rep_type: 
}, nofail = {_suppressions = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Suppressions::FileMatcher, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Suppressions::FileMatcher> > >::_Rep_type: 
}, userDefines = "", userUndefs = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, userIncludes = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Node: 
, configExcludePaths = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, reportProgress = false, library = {use = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, leakignore = std::__debug::set with 565 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, functionconst = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, functionpure = std::__debug::set with 296 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, useretval = std::__debug::set with 365 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, containers = std::__debug::map with 8 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::Container, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::Container> > >::_Rep_type: 
, argumentChecks = std::__debug::map with 639 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__debug::map<int, Library::ArgumentChecks, std::less<int>, std::allocator<std::pair<int const, Library::ArgumentChecks> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__debug::map<int, Library::ArgumentChecks, std::less<int>, std::allocator<std::pair<int const, Library::ArgumentChecks> > > > > >::_Rep_type: 
, returnuninitdata = std::__debug::set with 1 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, defines = std::__debug::vector of length 0, capacity 0, allocid = 9, _files = std::__debug::set with 2 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _alloc = std::__debug::map with 17 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::_Rep_type: 
, _dealloc = std::__debug::map with 6 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::_Rep_type: 
, _noreturn = std::__debug::map with 664 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > >::_Rep_type: 
, _ignorefunction = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _reporterrors = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > >::_Rep_type: 
, _processAfterCode = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > >::_Rep_type: 
, _markupExtensions = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _keywords = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >::_Rep_type: 
, _executableblocks = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::CodeBlock, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::CodeBlock> > >::_Rep_type: 
, _exporters = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::ExportedFunctions, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::ExportedFunctions> > >::_Rep_type: 
, _importers = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >::_Rep_type: 
, _reflection = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::_Rep_type: 
, _formatstr = std::__debug::map with 28 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<bool, bool>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::pair<bool, bool> > > >::_Rep_type: 
, podtypes = std::__debug::map with 116 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::PodType, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::PodType> > >::_Rep_type: 
, platform_types = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::PlatformType, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::PlatformType> > >::_Rep_type: 
, platforms = std::__debug::map with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Library::Platform, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Library::Platform> > >::_Rep_type: 
}, rules = empty std::__debug::listPython Exception <class 'ValueError'> Cannot find type std::__debug::list<Settings::Rule, std::allocator<Settings::Rule> >::_Node: 
, checkConfiguration = false, checkLibrary = false, standards = {c = Standards::C11, cpp = Standards::CPP11, posix = true}, sizeof_bool = 1, sizeof_short = 2, sizeof_int = 4, sizeof_long = 8, sizeof_long_long = 8, sizeof_float = 4, sizeof_double = 8, sizeof_long_double = 16, sizeof_wchar_t = 4, sizeof_size_t = 8, sizeof_pointer = 8, platformType = Settings::Unspecified}
#23 0x00000000007964da in main (argc=4, argv=0x7fffffffdd78) at cli/main.cpp:129
        exec = {<ErrorLogger> = {_vptr.ErrorLogger = 0xa26fb0 <vtable for CppCheckExecutor+16>}, _settings = 0x7fffffffd0c8, _errorList = std::__debug::set with 0 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rep_type: 
, _files = std::__debug::map with 1 elementsPython Exception <class 'ValueError'> Cannot find type std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >::_Rep_type: 
, time1 = 0, static exceptionOutput = <optimized out>, errorlist = false}


registers:
rax            0x0	0
rbx            0x7ffff791fc62	140737346927714
rcx            0xffffffffffffffff	-1
rdx            0x6	6
rsi            0xf992	63890
rdi            0xf992	63890
rbp            0xd40a20	0xd40a20 <stderr@@GLIBC_2.2.5>
rsp            0x7fffffffb3d8	0x7fffffffb3d8
r8             0x7ffff72c7960	140737340275040
r9             0x7ffff7fc9740	140737353914176
r10            0x8	8
r11            0x202	514
r12            0x7ffff0000950	140737219922256
r13            0x1	1
r14            0x0	0
r15            0x0	0
rip            0x7ffff6f36267	0x7ffff6f36267 <__GI_raise+55>
eflags         0x202	[ IF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0


current instructions:
=> 0x7ffff6f36267 <__GI_raise+55>:	cmp    $0xfffffffffffff000,%rax
   0x7ffff6f3626d <__GI_raise+61>:	ja     0x7ffff6f36290 <__GI_raise+96>
   0x7ffff6f3626f <__GI_raise+63>:	repz retq 
   0x7ffff6f36271 <__GI_raise+65>:	nopl   0x0(%rax)
   0x7ffff6f36278 <__GI_raise+72>:	test   %ecx,%ecx
   0x7ffff6f3627a <__GI_raise+74>:	jg     0x7ffff6f36257 <__GI_raise+39>
   0x7ffff6f3627c <__GI_raise+76>:	mov    %ecx,%edx
   0x7ffff6f3627e <__GI_raise+78>:	neg    %edx
   0x7ffff6f36280 <__GI_raise+80>:	and    $0x7fffffff,%ecx
   0x7ffff6f36286 <__GI_raise+86>:	cmove  %esi,%edx
   0x7ffff6f36289 <__GI_raise+89>:	mov    %edx,%ecx
   0x7ffff6f3628b <__GI_raise+91>:	jmp    0x7ffff6f36257 <__GI_raise+39>
   0x7ffff6f3628d <__GI_raise+93>:	nopl   (%rax)
   0x7ffff6f36290 <__GI_raise+96>:	mov    0x38ebd1(%rip),%rdx        # 0x7ffff72c4e68
   0x7ffff6f36297 <__GI_raise+103>:	neg    %eax
   0x7ffff6f36299 <__GI_raise+105>:	mov    %eax,%fs:(%rdx)


threads backtrace:

Thread 1 (Thread 0x7ffff7fc9740 (LWP 63890)):
#0  0x00007ffff6f36267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff6f37eca in __GI_abort () at abort.c:89
#2  0x00007ffff7879b5d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff78779a6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff78779f1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7877c09 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff78781ac in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x000000000078c126 in __gnu_cxx::new_allocator<char>::allocate (this=0x7fffffffba10, __n=8223699814931777825) at /usr/include/c++/5/ext/new_allocator.h:104
#8  0x000000000078aaa6 in std::allocator_traits<std::allocator<char> >::allocate (__a=..., __n=8223699814931777825) at /usr/include/c++/5/bits/alloc_traits.h:360
#9  0x0000000000788d6a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create (this=0x7fffffffba10, __capacity=@0x7fffffffb640: 8223699814931777824, __old_capacity=0) at /usr/include/c++/5/bits/basic_string.tcc:157
#10 0x00000000007899f2 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*> (this=0x7fffffffba10, __beg=0x2e64656c6c616320 <error: Cannot access memory at address 0x2e64656c6c616320>, __end=0xa084d8d58cd5ac40 <error: Cannot access memory at address 0xa084d8d58cd5ac40>) at /usr/include/c++/5/bits/basic_string.tcc:223
#11 0x00000000007879d2 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct_aux<char*> (this=0x7fffffffba10, __beg=0x2e64656c6c616320 <error: Cannot access memory at address 0x2e64656c6c616320>, __end=0xa084d8d58cd5ac40 <error: Cannot access memory at address 0xa084d8d58cd5ac40>) at /usr/include/c++/5/bits/basic_string.h:195
#12 0x000000000078561a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*> (this=0x7fffffffba10, __beg=0x2e64656c6c616320 <error: Cannot access memory at address 0x2e64656c6c616320>, __end=0xa084d8d58cd5ac40 <error: Cannot access memory at address 0xa084d8d58cd5ac40>) at /usr/include/c++/5/bits/basic_string.h:214
#13 0x0000000000783270 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (this=0x7fffffffba10, __str=<error: Cannot access memory at address 0x2e64656c6c616320>) at /usr/include/c++/5/bits/basic_string.h:398
#14 0x000000000089562f in std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int>::pair<unsigned int&, void> (this=0x7fffffffba10, __x=<error: Cannot access memory at address 0x2e64656c6c616320>, __y=@0x7fffffffb990: 0) at /usr/include/c++/5/bits/stl_pair.h:139
#15 0x00000000008956a8 in std::make_pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int&> (__x=<error: Cannot access memory at address 0x2e64656c6c616320>, __y=@0x7fffffffb990: 0) at /usr/include/c++/5/bits/stl_pair.h:281
#16 0x000000000088c2e2 in CheckStl::string_c_str (this=0x7fffffffbac0) at lib/checkstl.cpp:942
#17 0x000000000089473d in CheckStl::runSimplifiedChecks (this=0xd47c00 <_ZN12_GLOBAL__N_18instanceE>, tokenizer=0x7fffffffbdd0, settings=0x7fffffffd0c8, errorLogger=0x7fffffffd090) at lib/checkstl.h:59
#18 0x00000000008c83b3 in CppCheck::checkFile (this=0x7fffffffd090, code="( *const<> ( size_t ) ; foo ) { } * ( *const ( size_t ) ( ) ;> foo )< { }\n", FileName=0xd6d0a0 "crash327.cpp", checksums=std::__debug::set with 1 elements = {...}, internalErrorFound=@0x7fffffffc29b: false) at lib/cppcheck.cpp:398
#19 0x00000000008c6959 in CppCheck::processFile (this=0x7fffffffd090, filename="crash327.cpp", fileStream=...) at lib/cppcheck.cpp:239
#20 0x00000000008c5376 in CppCheck::check (this=0x7fffffffd090, path="crash327.cpp") at lib/cppcheck.cpp:70
#21 0x000000000078eff2 in CppCheckExecutor::check_internal (this=0x7fffffffdbc0, cppcheck=..., argv=0x7fffffffdd78) at cli/cppcheckexecutor.cpp:789
#22 0x000000000078dd13 in CppCheckExecutor::check (this=0x7fffffffdbc0, argc=4, argv=0x7fffffffdd78) at cli/cppcheckexecutor.cpp:183
#23 0x00000000007964da in main (argc=4, argv=0x7fffffffdd78) at cli/main.cpp:129
*/
